# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Somewhere', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood_name',
            field=models.CharField(default='Nameless', max_length=20),
        ),
    ]
